name: Blank Issue
description: Create a blank issue. ONLY USE THIS FORM IF YOU ARE A CONTRIBUTOR.

body:
  - type: markdown
    attributes:
      value: |
        # READ THIS BEFORE OPENING AN ISSUE

        This form is ONLY FOR DEVELOPERS. YOUR ISSUE WILL BE CLOSED AND YOU WILL POSSIBLY BE BLOCKED FROM THE REPOSITORY IF YOU IGNORE THIS.
        
        DO NOT USE THIS FORM, unless
        - you are a Vencord or RotCord contributor
        - you are filing a security related report

  - type: textarea
    id: content
    attributes:
      label: Content
    validations:
      required: true

  - type: checkboxes
    id: agreement-check
    attributes:
      label: Request Agreement
      options:
        - label: I have read the requirements for opening an issue above
          required: true
